INSERT INTO Topic (TopicName) VALUES ('Sports');
INSERT INTO Topic (TopicName) VALUES ('Geography');
INSERT INTO Topic (TopicName) VALUES ('History');
INSERT INTO Topic (TopicName) VALUES ('Science');
INSERT INTO Topic (TopicName) VALUES ('Music');
INSERT INTO Topic (TopicName) VALUES ('Arts');
INSERT INTO Topic (TopicName) VALUES ('General Knowledge');
INSERT INTO Topic (TopicName) VALUES ('Animals');
INSERT INTO Topic (TopicName) VALUES ('Food and Drink');
INSERT INTO Topic (TopicName) VALUES ('Film and TV');

INSERT INTO Quiz (QuizName) VALUES
('Sports Quiz'),
('Geography Quiz'),
('History Quiz'),
('Science Quiz'),
('Music Quiz'),
('Arts Quiz'),
('General Knowledge Quiz'),
('Animals Quiz'),
('Food and Drink Quiz'),
('Film and TV Quiz');

INSERT INTO QuestionType (TypeName, TypeInstruction) VALUES ('Multiple Choice', 'Choose the correct answerList.');
INSERT INTO QuestionType (TypeName, TypeInstruction) VALUES ('One answer', 'Enter the correct answer.');
INSERT INTO QuestionType (TypeName, TypeInstruction) VALUES ('Multiple Answers', 'Select all correct answers.');

INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many teams are there in the English Premier League?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which male tennis player holds the record for 36 consecutive grand slam quarter finals?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which NBA player holds the record for the most 3-pointers in a single season?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who is South Africa''s leading try scorer in rugby union?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which female tennis player holds the record for the most singles titles in the open era?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who is the all-time top goalscorer for the Spanish national football team?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which team did the San Francisco Giants beat to win the world series in 2014?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which country hosted the 2008 Summer Olympics?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who won the snooker world championship in the 2010?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who holds the current women''s 400m world record as of 2017?',1, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the capital of Namibia?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the world''s longest river?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the most populous country in Africa?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the highest peak in Europe?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the world''s deepest lake?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the capital of Peru?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year did Latvia become an EU member state?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many states are the in the USA?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Lanzarote is a member of which island group?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which is the largest of the Great Lakes in North America?',2, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year did the Titanic sink?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('For how many years did the Hundred Years War last?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The Great Pyramid of Giza is located in what Egyptian city?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What was the name of the US research and development project to create nuclear weapons in WWII?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Napoleon suffered defeat at Waterloo in what year?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Brazil was once a colony of which European country?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which Patriot leader organized the Boston Tea Party in 1773?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year did Fidel Castro die?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who was the mayor of New York City during the September 11 attacks in 2001?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Abraham Lincoln was assassinated in what year?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who was the court sculptor of Alexander the Great?',3, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many furlongs are in 1 mile?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who came up with the theories of General and Special relativity?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the second most abundant element in the universe?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which psychologist investigated obedience using electric shocks?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What vitamin is produced when a person is exposed to sunlight?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the name for a protein that acts as a biological catalyst?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which planet in our solar system has the most oxygen?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The European Organization for Nuclear Research is known by what four letter acronym?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What are the three base units of measurement in the metric system?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many planets in our solar system have moons?',4, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who is the lead singer for the American rock band Pearl Jam?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year was Nirvana''s first album, Bleach, released?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What was the highest selling album of the 1980s in the United States?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('"Hallelujah" is a song written by which Canadian recording artist?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year did Elvis Presley die?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what city was Ludwig van Beethoven born?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('New Orleans is known as the birthplace of what type of music?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who was the lead singer of the rock band Queen?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('ABBA was a pop group from what country?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which Italian composer won an Academy Award for The Hateful Eight score?',5, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the pseudonym of the Bristolian graffiti artist who branched into film this year?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who wrote the Booker Prize winning novel The Life of Pi?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which artistic movement was founded by Georges Braque and Pablo Picasso?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which artist frequently uses casts of his body in his work, and created The Angel of the North?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In Shakespeare''s Romeo and Juliet, what was Juliet''s family name?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which artist painted the Mona Lisa?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The use of canvas as a primary painting surface came of age in which century?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The uniforms of what Italian military force were originally designed by Michelangelo?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What mean-spirited miser is the central character in Charles Dickens'' A Christmas Carol?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What artist sold a balloon dog for $58.4 million?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who was the court sculptor of Alexander the Great?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who painted "The Scream"?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the main visual element in Impressionist painting?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What art movement employs aspects of mass culture, such as advertising, comic books and mundane cultural objects?',6, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the name of the island prison where, Nelson Mandela was imprisioned?',7, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the currency of Japan?',7, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who was Harry Houdini?',7, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the proper term for a group of parrots?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What animal has the largest ears?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is a group of lions called?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many hearts does an octopus have?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the sleepiest animal in the world, sleeping around 22 hours each day?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Polar bears feed mainly on what animal?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is a group of rhinoceros called?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The Alaskan Malamute is a type of what?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Natural pearls are found in what sea creature?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the fastest fish in the Ocean?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is a group of Crows called?',8, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the colloquial term for a rotating tray often often placed on a table to aid in distributing food?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What popular soda beverage was originally developed as a mixer for whiskey?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Sauerkraut is made from what finely cut vegetable?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the name for a confection that consists primarily of sugar or honey and almond meal?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The cooking technique that involves submerging food in a liquid at a relatively low temperature is called what?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is name of the scale used to measure the spicy heat of peppers?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Pho is a popular noodle soup from what country?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('The taste that allows us to taste savory foods is called what?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Chimichurri is a sauce that originated in what country?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is a traditional fermented Korean side dish made seasoned vegetables and salt?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('A tandoor is a type of what?',9, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is the name of the actress who plays Hermione Granger in the Harry Potter series of films?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('In what year was Alfred Hitchcock''s psychological thriller "Psycho" released?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What was the name of the kleptomaniac monkey in the Disney movie "Aladdin"?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is Michael J. Fox''s middle name?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who played James Bond in the 1969 film "On Her Majesty''s Secret Service"?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Keiko is the name of a whale that appeared in what 1993 American family drama film?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who played the female lead role in the 1986 sci-fi movie "Aliens"?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Rod Serling created what famous science fiction television show?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('On the hit show Seinfeld what was Kramer''s first name?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which actor played the captain of the Enterprise in the television series "Star Trek the Next Generation"?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What are the names of the two Muppet characters that heckle the rest of the cast from their balcony seats?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('How many fingers do the Simpsons cartoon characters have?',10, 1);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Choose the 3 types of blood cells.',7, 3);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which of the following are trigonometric functions?',7, 3);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Which of the following are Simpsons characters?',7, 3);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Will you give this submission a great review?',7, 3);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('What is President Obama''s first name?',7, 2);
INSERT INTO Question (Question, TopicID, TypeID) VALUES ('Who played Han Solo in Star Wars?',7, 2);

INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(1,'20',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(1,'18',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(1,'16',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(1,'22',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(2,'Roger Federer',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(2,'Rafael Nadal',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(2,'Pete Sampras',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(2,'Jimmy Connors',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(3,'Stephen Curry',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(3,'Ray Allen',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(3,'Clay Thompson',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(3,'Kyle Korver',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(4,'Bryan Habana',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(4,'Joost van der Westhuizen',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(4,'Jaque Fourie',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(4,'JP Pietersen',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(5,'Martina Navratilova',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(5,'Serena Williams',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(5,'Steffi Graf',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(5,'Jennifer Capriati',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(6,'David Villa',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(6,'David Silva',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(6,'Fernando Torres',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(6,'Raúl',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(7,'Kansas City Royals',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(7,'Detroit Tigers',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(7,'New York Yankees',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(7,'Boston Red Sox',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(8,'Beijing',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(8,'Sydney',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(8,'London',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(8,'Barcelona',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(9,'Neil Robertson',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(9,'Ronnie O''Sullivan',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(9,'Mark Williams',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(9,'Graeme Dott',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(10,'Marita Koch',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(10,'Allyson Felix',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(10,'Shaunae Miller',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(10,'Sanya Richards-Ross',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(11,'Windhoek',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(11,'Namibia City',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(11,'Cairo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(11,'Addis Ababa',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(12,'Amazon',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(12,'Nile',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(12,'Ganges',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(12,'Danube',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(13,'Nigeria',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(13,'South Africa',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(13,'Egypt',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(13,'Somalia',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(14,'Mount Elbrus',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(14,'Mont Blanc',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(14,'Mount Etna',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(14,'Mount Ararat',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(15,'Lake Baikal',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(15,'Lake Superior',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(15,'Caspian Sea',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(15,'Lake Victoria',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(16,'Lima',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(16,'Quito',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(16,'La Paz',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(16,'Santiago',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(17,'2004',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(17,'1998',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(17,'2008',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(17,'They aren''t in the EU',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(18,'50',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(18,'52',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(18,'49',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(18,'51',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(19,'Canary Islands',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(19,'Balearic Islands',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(19,'Lanzarote Islands',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(19,'Pelagie Islands',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(20,'Lake Superior',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(20,'Lake Huron',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(20,'Lake Michigan',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(20,'Lake Erie',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(21,'1912',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(21,'1922',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(21,'1914',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(21,'1905',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(22,'116',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(22,'100',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(22,'99',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(22,'200',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(23,'Giza',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(23,'Tunis',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(23,'Cairo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(23,'Alexandria',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(24,'Manhattan Project',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(24,'Brooklyn Research',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(24,'Manhattan Program',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(24,'Pentagon Research',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(25,'1815',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(25,'1915',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(25,'1715',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(25,'1615',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(26,'Portugal',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(26,'Spain',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(26,'France',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(26,'Great Britain',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(27,'Samuel Adams',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(27,'Abraham Lincoln',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(27,'John Adams',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(27,'George Washington',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(28,'2016',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(28,'2006',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(28,'1996',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(28,'2000',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(29,'Rudy Giuliani',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(29,'Michael Bloomberg',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(29,'Hilary Clinton',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(29,'David Dinkins',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(30,'1865',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(30,'1880',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(30,'1845',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(30,'1875',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(31,'Lysippus',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(31,'Praxiteles',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(31,'Apelles',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(31,'Vitruvius',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(32,'8',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(32,'18',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(32,'12',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(32,'9',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(33,'Albert Einstein',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(33,'Niels Bohr',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(33,'Issac Newton',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(33,'Stephen Hawking',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(34,'Hydrogen',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(34,'Oxygen',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(34,'Nitrogen',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(34,'Carbon',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(35,'Stanley Milgram',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(35,'Wilhelm Reich',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(35,'George H. Mead',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(35,'George Milgram',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(36,'Vitamin D',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(36,'Vitamin E',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(36,'Vitamin B',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(36,'Vitamin C',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(37,'Enzyme',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(37,'Glucose',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(37,'Adrenalin',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(37,'Testosterone',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(38,'Earth',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(38,'Mars',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(38,'Neptune',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(38,'Venus',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(39,'CERN',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(39,'EORN',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(39,'CREN',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(39,'NROE',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(40,'Metre, Litre and Gram',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(40,'Metre, Inch and Ounce',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(40,'Foot, Pint and Ounce',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(40,'Metre, Kilogram and Litre',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(41,'6',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(41,'9',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(41,'4',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(41,'1',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(42,'Eddie Vedder',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(42,'Chris Cornell',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(42,'Mike McCready',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(42,'Billy Corgan',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(43,'1989',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(43,'1991',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(43,'1999',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(43,'1993',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(44,'Thriller',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(44,'Born in the USA',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(44,'Purple Rain',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(44,'The Joshua Tree',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(45,'Leonard Cohen',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(45,'Neil Young',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(45,'Celine Dion',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(45,'Bryan Adams',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(46,'1977',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(46,'1983',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(46,'1973',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(46,'1967',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(47,'Bonn',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(47,'Vienna',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(47,'Berlin',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(47,'Prague',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(48,'Jazz',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(48,'Blues',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(48,'Soul',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(48,'Rock',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(49,'Freddie Mercury',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(49,'David Bowie',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(49,'Freddie Venus',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(49,'Mick Jagger',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(50,'Sweden',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(50,'Norway',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(50,'Denmark',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(50,'Finland',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(51,'Ennio Morricone',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(51,'Ludovico Einaudi',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(51,'Marco Ambrosini',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(51,'Paolo Longo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(52,'Banksy',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(52,'Inkie',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(52,'Inksy',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(52,'Banky',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(53,'Yann Martel',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(53,'Alice Kuipers',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(53,'Émile Martel',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(53,'Rafe Spall',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(54,'Cubism',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(54,'Impressionism',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(54,'Realism',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(54,'Pop Art',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(55,'Antony Gormley',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(55,'Anish Kapoor',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(55,'Damien Hirst',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(55,'Andy Goldsworthy',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(56,'Capulet',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(56,'Montague',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(56,'Escalus',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(56,'Sampson',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(57,'Leonardo da Vinci',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(57,'Michelangelo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(57,'Donatello',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(57,'Raphael',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(58,'16th',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(58,'15th',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(58,'14th',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(58,'17th',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(59,'Vatican Swiss Guards',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(59,'Italian Guards',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(59,'National Military',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(59,'Cavalry',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(60,'Ebenezer Scrooge',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(60,'Ebenezer Stooge',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(60,'Benedict Scrooge',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(60,'Benedict Stooge',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(61,'Jeff Koons',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(61,'Gerhart Richter',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(61,'Jasper Johns',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(61,'Christopher Wool',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(62,'Lysippus',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(62,'Praxiteles',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(62,'Apelles',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(62,'Vitruvius',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(63,'Edvard Munch',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(63,'Otto Meuller',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(63,'Vincent Van Gogh',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(63,'Wassily Kandinsky',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(64,'Color',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(64,'Line',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(64,'Pattern',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(64,'Shape',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(65,'Pop Art',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(65,'Art Deco',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(65,'Deconstructivism',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(65,'Les Automatistes',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(66,'Robben Island',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(66,'Rikers Island',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(66,'Seal Island',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(66,'Penal Colony Island',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(67,'Yen',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(67,'Japanese Dollars',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(67,'Riki',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(67,'Pounds',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(68,'An escapologist',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(68,'A famous poet',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(68,'A mafia boss',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(68,'A fighter pilot',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(69,'Pandemonium',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(69,'Pack',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(69,'Posse',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(69,'Party',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(70,'African Elephant',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(70,'Indian Elephant',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(70,'Giant Manta Ray',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(70,'Giraffe',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(71,'Pride',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(71,'Pack',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(71,'Herd',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(71,'Flock',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(72,'Three',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(72,'Five',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(72,'One',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(72,'None',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(73,'Koala',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(73,'Sloth',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(73,'Brown Bear',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(73,'Moth',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(74,'Seals',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(74,'Penguins',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(74,'Humans',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(74,'They are herbivores',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(75,'Crash',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(75,'Collection',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(75,'Cacophany',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(75,'Company',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(76,'Dog',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(76,'Wolf',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(76,'Bear',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(76,'Goat',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(77,'Oysters',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(77,'Mussels',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(77,'Sea snails',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(77,'Cockles',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(78,'Sailfish',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(78,'Flying fish',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(78,'Marlin',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(78,'Wahoo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(79,'Murder',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(79,'Flock',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(79,'Swarm',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(79,'Gaggle',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(80,'Lazy Susan',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(80,'Lazy Susie',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(80,'Lazy Sarah',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(80,'Susie Belt',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(81,'Mountain Dew',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(81,'Ginger Ale',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(81,'7up',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(81,'Sprite',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(82,'Cabbage',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(82,'Lettuce',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(82,'Carrot',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(82,'Onion',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(83,'Marzipan',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(83,'Almond milk',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(83,'Nougat',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(83,'Almond butter',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(84,'Poaching',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(84,'Boiling',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(84,'Sous-vide',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(84,'Steaming',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(85,'Scoville scale',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(85,'Chilli scale',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(85,'Heat scale',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(85,'Carroll scale',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(86,'Vietnam',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(86,'Thailand',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(86,'Singapore',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(86,'China',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(87,'Umami',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(87,'Sensory bud',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(87,'Saltiness',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(87,'Unimi',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(88,'Argentina',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(88,'Mexico',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(88,'Chile',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(88,'Colombia',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(89,'Kimchi',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(89,'Chimki',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(89,'Kimichi',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(89,'Kochi',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(90,'Oven',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(90,'Kebab',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(90,'Curry',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(90,'Pot',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(91,'Emma Watson',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(91,'Emma Thompson',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(91,'Heather Watson',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(91,'Heather Thompson',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(92,'1960',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(92,'1970',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(92,'1965',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(92,'1955',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(93,'Abu',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(93,'Abo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(93,'Apu',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(93,'Lou',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(94,'Andrew',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(94,'John',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(94,'Jack',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(94,'William',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(95,'George Lazenby',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(95,'Roger Moore',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(95,'Sean Connery',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(95,'Timothy Dalton',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(96,'Free Willy',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(96,'Moby Dick',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(96,'The Great Whale',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(96,'Deep Blue Sea',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(97,'Sigourney Weaver',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(97,'Ellen Ripney',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(97,'Jamie Lee Curtis',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(97,'Jodie Foster',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(98,'Twilight Zone',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(98,'Star Trek',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(98,'Firefly',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(98,'Quantum Leap',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(99,'Cosmo',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(99,'He didn''t have one',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(99,'Kenny',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(99,'Colo',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(100,'Patrick Stewart',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(100,'William Shatner',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(100,'Leonard Nimoy',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(100,'Jean-Luc Picard',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(101,'Statler and Waldorf',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(101,'Waldorf and Ceasar',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(101,'Sandler and Waldorf',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(101,'Statler and Wally',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(102,'Four',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(102,'Five',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(102,'Three',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(102,'Six',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(103,'White Blood Cels',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(103,'Red Blood Cells',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(103,'Amoeba',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(103,'Platelets',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(104,'Sine',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(104,'Tango',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(104,'Cosine',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(104,'Sector',0);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(105,'Bart',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(105,'Maggie',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(105,'Homer',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(105,'Apu',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(106,'Yes',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(106,'Of course',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(106,'I will',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(106,'Sure',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(107,'Barack',1);
INSERT INTO Options (QuestionID, OptionText, IsCorrect) VALUES(108,'Harrison Ford',1);



INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(1, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(2, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(3, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(4, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(5, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(6, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(7, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(8, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(9, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(10, 1);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(11, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(12, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(13, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(14, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(15, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(16, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(17, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(18, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(19, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(20, 2);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(21, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(22, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(23, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(24, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(25, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(26, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(27, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(28, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(29, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(30, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(31, 3);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(32, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(33, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(34, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(35, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(36, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(37, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(38, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(39, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(40, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(41, 4);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(42, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(43, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(44, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(45, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(46, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(47, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(48, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(49, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(50, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(51, 5);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(52, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(53, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(54, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(55, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(56, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(57, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(58, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(59, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(60, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(61, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(62, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(63, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(64, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(65, 6);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(66, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(67, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(68, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(69, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(70, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(71, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(72, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(73, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(74, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(75, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(76, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(77, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(78, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(79, 8);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(80, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(81, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(82, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(83, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(84, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(85, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(86, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(87, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(88, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(89, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(90, 9);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(91, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(92, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(93, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(94, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(95, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(96, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(97, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(98, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(99, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(100, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(101, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(102, 10);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(103, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(104, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(105, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(106, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(107, 7);
INSERT INTO QuestionQuiz (QuestionID, QuizID) VALUES(108, 7);